web:
    image: nginx:latest
    ports:
        - "127.0.0.1:2137:80"
    volumes:
        - ../:/var/www
        - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
php:
    image: php:7.2-rc-fpm
    working_dir: /var/www
    volumes:
        - ../:/var/www
    links:
        - postgres

postgres:
    image: postgres:9.6
    ports:
        - 2138:5432
    environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root