kartadan_api:
    image: nginx:latest
    ports:
        - 127.0.0.1:2137:80
    volumes:
        - ../api:/var/www
        - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
        - kartadan_php

kartadan_php:
    image: php:7.2-rc-fpm
    working_dir: /var/www
    volumes:
        - ../api:/var/www
    links:
        - kartadan_postgres

kartadan_postgres:
    image: postgres:9.6
    ports:
        - 127.0.0.1:2138:5432
    environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=kartadan